version: '3.1'

services:

  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    expose:
    - "3306"
    environment:
      MYSQL_DATABASE: shop
      MYSQL_ROOT_PASSWORD: admin

  webshop:
    image: supermon/webshop
    restart: always
    ports:
    - 8080:8080
    depends_on:
    - db
    links:
    - db

